/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmModal: typeof import('./components/ui/ConfirmModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./components/ui/UiButton.vue')['default']
    UiCard: typeof import('./components/ui/UiCard.vue')['default']
    UiChip: typeof import('./components/ui/UiChip.vue')['default']
    UiDivider: typeof import('./components/ui/UiDivider.vue')['default']
    UiIconButton: typeof import('./components/ui/UiIconButton.vue')['default']
    UiSlider: typeof import('./components/ui/UiSlider.vue')['default']
    UiTooltip: typeof import('./components/ui/UiTooltip.vue')['default']
  }
}
